version: v1
services:
  auth: PESAGUARD_AUTH_SERVICE_URL
  organizations: PESAGUARD_ORGANIZATIONS_SERVICE_URL
  merchants: PESAGUARD_MERCHANTS_SERVICE_URL
  payments: PESAGUARD_PAYMENTS_SERVICE_URL
  reconciliation: PESAGUARD_RECONCILIATION_SERVICE_URL
  notifications: PESAGUARD_NOTIFICATIONS_SERVICE_URL
