from __future__ import annotations

from datetime import timedelta

from shared.configuration.constants import DEFAULT_CONFIG_FILE_NAME, DEFAULT_CONFIG_DIR, DEFAULT_DATABASE_PORT, DEFAULT_LOG_LEVEL, DEFAULT_REDIS_PORT


DEFAULT_ENVIRONMENT = "development"
DEFAULT_CONFIG_FILE = DEFAULT_CONFIG_FILE_NAME
DEFAULT_CONFIG_DIRECTORY = DEFAULT_CONFIG_DIR
DEFAULT_CONFIG_VERSION = "1.0"
DEFAULT_LOGGING_LEVEL = DEFAULT_LOG_LEVEL
DEFAULT_DATABASE_CONNECT_TIMEOUT = 10
DEFAULT_DATABASE_POOL_SIZE = 20
DEFAULT_REDIS_DB = 0
DEFAULT_REDIS_TIMEOUT_SECONDS = 5
DEFAULT_REDIS_MAX_CONNECTIONS = 50
DEFAULT_CACHE_TTL_SECONDS = 300
DEFAULT_SCRAPE_INTERVAL_SECONDS = 15
DEFAULT_TELEMETRY_SAMPLE_RATE = 0.2
DEFAULT_SCHEDULER_INTERVAL_SECONDS = 60
DEFAULT_SCHEDULER_RETRY_ATTEMPTS = 3
DEFAULT_SCHEDULER_BACKOFF_SECONDS = 5
DEFAULT_SECRET_MIN_LENGTH = 32
DEFAULT_FEATURE_FLAGS = {
    "enable_experimental_payments": False,
    "enable_service_mesh": True,
    "enable_rate_limiting": True,
    "enable_caching": True,
}
DEFAULT_STORAGE_BASE_PATH = "/var/lib/pesaguard/storage"
DEFAULT_EMAIL_FROM_ADDRESS = "no-reply@pesaguard"
DEFAULT_API_PAGE_SIZE = 50
DEFAULT_API_PAGE_MAX_SIZE = 250
DEFAULT_RETRY_ATTEMPTS = 3
DEFAULT_RETRY_BACKOFF_SECONDS = 2
DEFAULT_HTTP_TIMEOUT_SECONDS = 10
DEFAULT_MAX_CONCURRENT_REQUESTS = 500
DEFAULT_LOG_FILE_PATH = "/var/log/pesaguard/app.log"
DEFAULT_LOG_ROTATION_SIZE_MB = 50
DEFAULT_LOG_BACKUP_COUNT = 5
DEFAULT_ENCRYPTION_ALGORITHM = "AES-256-GCM"
DEFAULT_PASSWORD_SALT_ROUNDS = 12
DEFAULT_ENVIRONMENT_LABELS = {
    "development": "Development",
    "testing": "Testing",
    "staging": "Staging",
    "production": "Production",
}
