apiVersion: v1
kind: Service
metadata:
  name: pesaguard-gateway
  labels:
    app.kubernetes.io/name: pesaguard-gateway
spec:
  selector:
    app.kubernetes.io/name: pesaguard-gateway
  ports:
    - name: https
      port: 443
      targetPort: 8443
  type: ClusterIP
